# elliott is synced from openshift-eng/elliott to ashwindasr/art-tools#elliott every 6 hrs

name: elliott sync

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch: {}

jobs:
  forward-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push Commits
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add source https://github.com/openshift-eng/elliott.git
          git fetch source
          git push origin source/master:elliott # Pushing to the "elliott" branch in the second repository
