name: Unit tests

on:
  pull_request:
    branches: [ master ]

jobs:
  doozer:
    runs-on: ubuntu-latest
    container: fedora:37
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install packages
        run: cd doozer && dnf install -y gcc krb5-devel
      - name: Create venv and install dependencies
        run: cd doozer && make venv
      - name: Run tests
        run: cd doozer && make test
  elliott:
    runs-on: ubuntu-latest
    container: fedora:37
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install packages
        run: cd elliott && dnf install -y gcc krb5-devel
      - name: Create venv and install dependencies
        run: cd elliott && make venv
      - name: Run tests
        run: cd elliott && make test
